export default {
    components: {
        H1: {
            core: {},
            xs: {},
            s: {},
            m: {},
            l: {},
            xl: {},
        },
        H2: {
            core: {},
            xs: {},
            s: {},
            m: {},
            l: {},
            xl: {},
        },
        H3: {
            core: {},
            xs: {},
            s: {},
            m: {},
            l: {},
            xl: {},
        },
        H4: {
            core: {},
            xs: {},
            s: {},
            m: {},
            l: {},
            xl: {},
        },
        H5: {
            core: {},
            xs: {},
            s: {},
            m: {},
            l: {},
            xl: {},
        },
        H6: {
            core: {},
            xs: {},
            s: {},
            m: {},
            l: {},
            xl: {},
        },
        P: {
            core: {},
            xs: {},
            s: {},
            m: {},
            l: {},
            xl: {},
        },
    }
};